#!/usr/bin/env bash

# Why this file, you ask? Because lazy.

cd ~/.config.d
vim .
git commit -a

# This is *kind* of silly - it should be replaced by asking whether to run the configuration again.
configure "$@"
